"""
Metals Seasonality Dashboard
=============================
Cloud-ready Streamlit dashboard. Reads pre-fetched data from a Parquet file
(generated by fetcher.py on a Bloomberg machine). No Bloomberg dependency.
"""

import os
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime

# ──────────────────────────────────────────────────── page config
st.set_page_config(
    page_title="Metals Seasonality Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────────── paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "DIM_METALS_DESCRIPTION.csv")
PARQUET_PATH = os.path.join(BASE_DIR, "data", "metals_data.parquet")

# ──────────────────────────────────────────────────── load data


@st.cache_data
def load_meta():
    df = pd.read_csv(CSV_PATH)
    for c in df.select_dtypes("object"):
        df[c] = df[c].str.strip().str.strip('"')
    return df


@st.cache_data
def load_data():
    if not os.path.exists(PARQUET_PATH):
        return None
    df = pd.read_parquet(PARQUET_PATH)
    df["date"] = pd.to_datetime(df["date"])
    return df


meta = load_meta()
data = load_data()

if data is None:
    st.error(
        "**No data file found.**\n\n"
        "Run `python fetcher.py` on a machine with Bloomberg Terminal first, "
        "then commit `data/metals_data.parquet` to the repo."
    )
    st.stop()

# ──────────────────────────────────────────────────── tab order
_ORDER = [
    "Copper", "Aluminium", "Zinc", "Nickel", "Lead", "Tin",
    "Alumina", "Bauxite", "Laterite", "Demand",
]
_all = meta["METALS"].unique().tolist()
metals_list = [m for m in _ORDER if m in _all] + sorted(set(_all) - set(_ORDER))

# ──────────────────────────────────────────────────── sidebar
st.sidebar.title("Settings")

NOW = datetime.now()
CURRENT_YEAR = NOW.year

# detect available years from data
data_min_year = int(data["date"].dt.year.min())
data_max_year = int(data["date"].dt.year.max())

n_years = st.sidebar.slider(
    "Years of history", 3, min(15, data_max_year - data_min_year), 8
)
START_YEAR = max(data_max_year - n_years, data_min_year)

all_years = list(range(START_YEAR, data_max_year + 1))
highlight_years = st.sidebar.multiselect(
    "Highlight years",
    all_years,
    default=[y for y in [data_max_year, data_max_year - 1] if y in all_years],
)

# ──────────────────────────────────────────────────── data helpers


def get_ticker_data(ticker: str) -> pd.DataFrame | None:
    """Get data for a single ticker, filtered by year range."""
    sub = data[data["ticker"] == ticker].copy()
    sub = sub[sub["date"].dt.year >= START_YEAR]
    return sub if not sub.empty else None


# ──────────────────────────────────────────────────── chart builder


def _ref_date(d):
    """Map any date into year-2000 for seasonal overlay (2000 is a leap year)."""
    try:
        return d.replace(year=2000)
    except ValueError:
        return d.replace(year=2000, month=2, day=28)


def seasonality_chart(df: pd.DataFrame, title: str, units: str, hl_years: list):
    tmp = df.copy()
    tmp["year"] = tmp["date"].dt.year
    tmp["ref"] = tmp["date"].apply(_ref_date)

    years = sorted(tmp["year"].unique())
    n = len(years)

    if n > 1:
        scale = px.colors.sample_colorscale(
            "Turbo", [0.05 + 0.90 * i / (n - 1) for i in range(n)]
        )
    else:
        scale = ["#1f77b4"]
    year_color = dict(zip(years, scale))

    fig = go.Figure()
    for yr in years:
        sub = tmp[tmp["year"] == yr].sort_values("ref")
        hl = yr in hl_years
        fig.add_trace(
            go.Scatter(
                x=sub["ref"],
                y=sub["value"],
                name=str(yr),
                mode="lines",
                line=dict(
                    width=2.8 if hl else 1.0,
                    color=year_color[yr],
                ),
                opacity=1.0 if hl else 0.45,
                hovertemplate=(
                    f"<b>{yr}</b>  %{{x|%b %d}}: %{{y:,.2f}}<extra></extra>"
                ),
            )
        )

    fig.update_layout(
        title=dict(text=title, font_size=13),
        xaxis=dict(
            tickformat="%b",
            dtick="M1",
            range=["2000-01-01", "2000-12-31"],
        ),
        yaxis_title=units,
        hovermode="x unified",
        height=370,
        margin=dict(l=50, r=10, t=55, b=30),
        legend=dict(
            orientation="h",
            y=1.12,
            x=0.5,
            xanchor="center",
            font_size=9,
            tracegroupgap=0,
        ),
        template="plotly_white",
    )
    return fig


# ──────────────────────────────────────────────────── main area
st.title("Metals Seasonality Dashboard")

# last-updated info
parquet_mtime = datetime.fromtimestamp(os.path.getmtime(PARQUET_PATH))
st.caption(
    f"Data window: {START_YEAR} -- {data_max_year}  |  "
    f"Source: Bloomberg  |  Last updated: {parquet_mtime.strftime('%Y-%m-%d %H:%M')}"
)

tabs = st.tabs(metals_list)

for tab_obj, metal in zip(tabs, metals_list):
    with tab_obj:
        subset = meta[meta["METALS"] == metal]
        types = sorted(subset["TYPE"].unique())

        if not types:
            st.info("No indicators for this metal.")
            continue

        sel_type = st.radio(
            "Indicator type",
            types,
            horizontal=True,
            key=f"radio_{metal}",
        )

        rows = subset[subset["TYPE"] == sel_type]

        cols = st.columns(2)
        ci = 0
        for _, r in rows.iterrows():
            ticker = r["TICKER_BLOOMBERG"]
            df = get_ticker_data(ticker)
            if df is None:
                continue
            with cols[ci % 2]:
                fig = seasonality_chart(
                    df,
                    r["DESCRIPTION"],
                    r["UNITS"],
                    highlight_years,
                )
                st.plotly_chart(fig, use_container_width=True, key=f"c_{metal}_{ticker}")
            ci += 1

        if ci == 0:
            st.warning("No data available for selected indicators.")
