"""
Vista Capital - Metals Dashboard
=================================
Cloud-ready Streamlit dashboard. Reads pre-fetched data from a Parquet file
(generated by fetcher.py on a Bloomberg machine). No Bloomberg dependency.
"""

import os
import re
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime

# ──────────────────────────────────────────────────── page config
st.set_page_config(
    page_title="Vista Capital - Metals Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ──────────────────────────────────────────────────── paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "DIM_METALS_DESCRIPTION.csv")
PARQUET_PATH = os.path.join(BASE_DIR, "data", "metals_data.parquet")

# ──────────────────────────────────────────────────── load data


@st.cache_data
def load_meta():
    df = pd.read_csv(CSV_PATH)
    for c in df.select_dtypes("object"):
        df[c] = df[c].str.strip().str.strip('"')
    return df


@st.cache_data
def load_data():
    if not os.path.exists(PARQUET_PATH):
        return None
    df = pd.read_parquet(PARQUET_PATH)
    df["date"] = pd.to_datetime(df["date"])
    return df


meta = load_meta()
data = load_data()

if data is None:
    st.error(
        "**No data file found.**\n\n"
        "Run `python fetcher.py` on a machine with Bloomberg Terminal first, "
        "then commit `data/metals_data.parquet` to the repo."
    )
    st.stop()

# ──────────────────────────────────────────────────── tab order
_ORDER = [
    "Copper", "Aluminium", "Zinc", "Nickel", "Lead", "Tin",
    "Alumina", "Bauxite", "Laterite", "Demand",
]
_all = meta["METALS"].unique().tolist()
metals_list = [m for m in _ORDER if m in _all] + sorted(set(_all) - set(_ORDER))

# ──────────────────────────────────────────────────── sidebar
st.sidebar.title("Settings")

NOW = datetime.now()
CURRENT_YEAR = NOW.year

# detect available years from data
data_min_year = int(data["date"].dt.year.min())
data_max_year = int(data["date"].dt.year.max())

n_years = st.sidebar.slider(
    "Years of history", 3, min(15, data_max_year - data_min_year), 8
)
START_YEAR = max(data_max_year - n_years, data_min_year)

all_years = list(range(START_YEAR, data_max_year + 1))
highlight_years = st.sidebar.multiselect(
    "Highlight years",
    all_years,
    default=[y for y in [data_max_year, data_max_year - 1] if y in all_years],
)

# ──────────────────────────────────────────────────── data helpers


def get_ticker_data(ticker: str) -> pd.DataFrame | None:
    """Get data for a single ticker, filtered by year range."""
    sub = data[data["ticker"] == ticker].copy()
    sub = sub[sub["date"].dt.year >= START_YEAR]
    return sub if not sub.empty else None


# ──────────────────────────────────────────────────── chart builders


def _ref_date(d):
    """Map any date into year-2000 for seasonal overlay (2000 is a leap year)."""
    try:
        return d.replace(year=2000)
    except ValueError:
        return d.replace(year=2000, month=2, day=28)


def seasonality_chart(df: pd.DataFrame, title: str, units: str, hl_years: list):
    """Seasonality chart with one line per year."""
    tmp = df.copy()
    tmp["year"] = tmp["date"].dt.year
    tmp["ref"] = tmp["date"].apply(_ref_date)

    years = sorted(tmp["year"].unique())
    n = len(years)

    if n > 1:
        scale = px.colors.sample_colorscale(
            "Turbo", [0.05 + 0.90 * i / (n - 1) for i in range(n)]
        )
    else:
        scale = ["#1f77b4"]
    year_color = dict(zip(years, scale))

    fig = go.Figure()
    for yr in years:
        sub = tmp[tmp["year"] == yr].sort_values("ref")
        hl = yr in hl_years
        fig.add_trace(
            go.Scatter(
                x=sub["ref"],
                y=sub["value"],
                name=str(yr),
                mode="lines",
                line=dict(
                    width=2.8 if hl else 1.0,
                    color=year_color[yr],
                ),
                opacity=1.0 if hl else 0.45,
                hovertemplate=(
                    f"<b>{yr}</b>  %{{x|%b %d}}: %{{y:,.2f}}<extra></extra>"
                ),
            )
        )

    fig.update_layout(
        title=dict(text=title, font_size=13),
        xaxis=dict(
            tickformat="%b",
            dtick="M1",
            range=["2000-01-01", "2000-12-31"],
        ),
        yaxis_title=units,
        hovermode="x unified",
        height=370,
        margin=dict(l=50, r=10, t=55, b=30),
        legend=dict(
            orientation="h",
            y=1.12,
            x=0.5,
            xanchor="center",
            font_size=9,
            tracegroupgap=0,
        ),
        template="plotly_white",
    )
    return fig


def line_chart(df: pd.DataFrame, title: str, units: str):
    """Simple time-series line chart for Price type."""
    tmp = df.sort_values("date")
    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=tmp["date"],
            y=tmp["value"],
            mode="lines",
            line=dict(width=1.5, color="#1f77b4"),
            hovertemplate="%{x|%Y-%m-%d}: %{y:,.2f}<extra></extra>",
        )
    )
    fig.update_layout(
        title=dict(text=title, font_size=13),
        yaxis_title=units,
        hovermode="x unified",
        height=370,
        margin=dict(l=50, r=10, t=55, b=30),
        template="plotly_white",
    )
    return fig


def price_curve_chart(curve_rows, all_data, metal, custom_date=None):
    """
    Forward curve chart: x = tenor (months), y = price.
    Shows current curve vs 1W, 1M, 3M, 6M, 1Y ago + optional custom date.
    """
    # Parse tenor months from descriptions
    tenors = []
    for _, r in curve_rows.iterrows():
        match = re.search(r"(\d+)M", r["DESCRIPTION"])
        if match:
            tenors.append({
                "ticker": r["TICKER_BLOOMBERG"],
                "months": int(match.group(1)),
            })
    if not tenors:
        return None

    tenors.sort(key=lambda t: t["months"])
    units = curve_rows.iloc[0]["UNITS"]

    # Get data for all curve tickers
    curve_tickers = [t["ticker"] for t in tenors]
    cdata = all_data[all_data["ticker"].isin(curve_tickers)].copy()
    if cdata.empty:
        return None

    # Pivot: date × ticker
    pivot = cdata.pivot_table(index="date", columns="ticker", values="value")
    available_dates = pivot.index.sort_values()
    latest = available_dates.max()

    # Define comparison offsets
    offsets = [
        ("Current", pd.DateOffset(0)),
        ("1W ago", pd.DateOffset(weeks=1)),
        ("1M ago", pd.DateOffset(months=1)),
        ("3M ago", pd.DateOffset(months=3)),
        ("6M ago", pd.DateOffset(months=6)),
        ("1Y ago", pd.DateOffset(years=1)),
    ]

    # Resolve each offset to nearest available date
    ref_curves = {}
    for label, offset in offsets:
        target = latest - offset
        prior = available_dates[available_dates <= target]
        if not prior.empty:
            actual = prior.max()
            ref_curves[f"{label} ({actual.strftime('%Y-%m-%d')})"] = actual

    # Add custom date
    if custom_date is not None:
        target = pd.Timestamp(custom_date)
        prior = available_dates[available_dates <= target]
        if not prior.empty:
            actual = prior.max()
            ref_curves[f"Custom ({actual.strftime('%Y-%m-%d')})"] = actual

    # Build chart
    fig = go.Figure()
    colors = [
        "#e41a1c", "#377eb8", "#4daf4a", "#984ea3",
        "#ff7f00", "#a65628", "#f781bf", "#999999",
    ]

    for i, (label, ref_date) in enumerate(ref_curves.items()):
        if ref_date not in pivot.index:
            continue
        row = pivot.loc[ref_date]

        x_vals, y_vals = [], []
        for t in tenors:
            if t["ticker"] in row.index and pd.notna(row[t["ticker"]]):
                x_vals.append(t["months"])
                y_vals.append(row[t["ticker"]])

        is_current = label.startswith("Current")
        is_custom = label.startswith("Custom")
        fig.add_trace(
            go.Scatter(
                x=x_vals,
                y=y_vals,
                name=label,
                mode="lines+markers",
                line=dict(
                    width=3 if is_current else 2 if is_custom else 1.5,
                    color=colors[i % len(colors)],
                    dash="solid" if is_current else "dash" if is_custom else "solid",
                ),
                marker=dict(size=5 if is_current else 4),
                opacity=1.0 if is_current else 0.8,
            )
        )

    fig.update_layout(
        title=dict(text=f"{metal} Forward Curve", font_size=15),
        xaxis_title="Tenor (months)",
        xaxis=dict(dtick=1),
        yaxis_title=units,
        hovermode="x unified",
        height=500,
        margin=dict(l=50, r=10, t=55, b=40),
        legend=dict(
            orientation="h",
            y=1.15,
            x=0.5,
            xanchor="center",
            font_size=10,
        ),
        template="plotly_white",
    )
    return fig


# ──────────────────────────────────────────────────── main area
st.title("Vista Capital - Metals Dashboard")

# last-updated info
parquet_mtime = datetime.fromtimestamp(os.path.getmtime(PARQUET_PATH))
st.caption(
    f"Data window: {START_YEAR} -- {data_max_year}  |  "
    f"Source: Bloomberg  |  Last updated: {parquet_mtime.strftime('%Y-%m-%d %H:%M')}"
)

tabs = st.tabs(metals_list)

for tab_obj, metal in zip(tabs, metals_list):
    with tab_obj:
        subset = meta[meta["METALS"] == metal]
        types = sorted(subset["TYPE"].unique())

        if not types:
            st.info("No indicators for this metal.")
            continue

        sel_type = st.radio(
            "Indicator type",
            types,
            horizontal=True,
            key=f"radio_{metal}",
        )

        rows = subset[subset["TYPE"] == sel_type]

        # ── Price Curve: single forward-curve chart ──────────
        if sel_type == "Price Curve":
            add_custom = st.toggle(
                "Add custom date to curve",
                key=f"toggle_curve_{metal}",
            )
            custom_dt = None
            if add_custom:
                min_date = data["date"].min().date()
                max_date = data["date"].max().date()
                custom_dt = st.date_input(
                    "Select date",
                    value=max_date - pd.DateOffset(months=2),
                    min_value=min_date,
                    max_value=max_date,
                    key=f"curve_date_{metal}",
                )

            fig = price_curve_chart(rows, data, metal, custom_date=custom_dt)
            if fig:
                st.plotly_chart(fig, use_container_width=True, key=f"curve_{metal}")
            else:
                st.warning("No data available for price curve.")

        # ── Price: normal line charts ────────────────────────
        elif sel_type == "Price":
            cols = st.columns(2)
            ci = 0
            for _, r in rows.iterrows():
                ticker = r["TICKER_BLOOMBERG"]
                df = get_ticker_data(ticker)
                if df is None:
                    continue
                with cols[ci % 2]:
                    fig = line_chart(df, r["DESCRIPTION"], r["UNITS"])
                    st.plotly_chart(
                        fig, use_container_width=True, key=f"c_{metal}_{ticker}"
                    )
                ci += 1
            if ci == 0:
                st.warning("No data available for selected indicators.")

        # ── All other types: seasonality charts ──────────────
        else:
            cols = st.columns(2)
            ci = 0
            for _, r in rows.iterrows():
                ticker = r["TICKER_BLOOMBERG"]
                df = get_ticker_data(ticker)
                if df is None:
                    continue
                with cols[ci % 2]:
                    fig = seasonality_chart(
                        df, r["DESCRIPTION"], r["UNITS"], highlight_years,
                    )
                    st.plotly_chart(
                        fig, use_container_width=True, key=f"c_{metal}_{ticker}"
                    )
                ci += 1
            if ci == 0:
                st.warning("No data available for selected indicators.")
